services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:PyV0f7GsfsxHUgDeldMTNFsGS5P6ugPdiDi2fsNb+Wk=
      APP_URL: http://localhost:4000
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: examenes
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: examenes
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database:/docker-entrypoint-initdb.d:ro

volumes:
  postgres_data:
